### ISSUE TITLE
how can i use it with lumen? is lumen supported?

### ISSUE THREAD

**Issue by codeitlikemiley** [noh4ck/laravel-graphiql#6]

**Comment by Nohac** [comment]
I don't think this will work with lumen, not sure what the requirements is for that. I don't really use this anymore so I'm probably not going to look in to this. A pull request is welcome.

**Comment by codeitlikemiley** [comment]
im just wondering if i can implement this on lumen, but if not its ok.. i havent look into lumen yet also...
but its just my other option to boost performance... since i will want to just use it for api...
it has higher request rate per sec than laravel

im wanna use the following stack for performance
lumen for backend, monggoDb for database/queque, redis for cache/pubsub,, nuxt for ssr , vue , vuetify for front end, grapql for api

if this is not compatible to lumen then i guess i dont have to change anything in my current laravel set up...

thanks for this package, i can easily test my grapql endpoints hope you keep maintaining this ty

**Comment by Nohac** [comment]
As long as people are interested in keeping this alive, I will keep accepting pull requests. Thank you for your feedback and good luck with your project!
